permalink: date

sass:
  sass_dir: stylesheets

encoding: "utf-8"

collections:
  bread:
    output: true
  garden:
    output: true
  notes:
    output: true

kramdown:
  input: GFM
  hard_wrap: false

exclude:
  - node_modules

plugins:
  - jekyll-feed
